// Generated by CoffeeScript 1.6.1
(function() {

  define(["util/vec"], function(vec) {
    return {
      Sphere: function(radius, atmo) {
        var atmoMaterial, planet, rings, segments, surface, surfaceMaterial;
        segments = 16 * 6;
        rings = 16 * 2;
        planet = new THREE.Object3D();
        surfaceMaterial = new THREE.MeshPhongMaterial({
          map: THREE.ImageUtils.loadTexture(texture)
        });
        surface = new THREE.Mesh(new THREE.SphereGeometry(radius, segments, rings), surfaceMaterial);
        atmoMaterial = new THREE.MeshPhongMaterial({
          color: atmo,
          opacity: 0.2
        });
        atmo = new THREE.Mesh(new THREE.SphereGeometry(radius * 0.1, segments, rings), atmoMaterial);
        planet.add(surface);
        planet.add(atmo);
        planet.update = function(t) {
          var s;
          s = 0.005 * t;
          return surface.rotation = vec(0, s, 0);
        };
        return planet;
      }
    };
  });

}).call(this);
